# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = ../obj/Debug/test.coverage
  TARGETDIR  = ../bin/Debug
  TARGET     = $(TARGETDIR)/test.coverage
  DEFINES   += -DDEBUG -D_DEBUG -DPLATFORM_CHECKED -DUNIX_BUILD
  INCLUDES  += -Iinclude/cppunit -Iinclude/gmock -Iinclude/lua -Iinclude -I/usr/local/include -I/usr/include -I../include -Ibind_classes -Icpp_classes -Itest_classes
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -W -Wall -ansi -pedantic -std=c++98 -fprofile-arcs -ftest-coverage
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -Lusr/local/lib -Lusr/lib
  LIBS      += -lgmock -lpthread -lcppunit -llua -ldl -lgcov
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running post-build commands
	$(TARGET)
  endef
endif

ifeq ($(config),release)
  OBJDIR     = ../obj/Release/test.coverage
  TARGETDIR  = ../bin/Release
  TARGET     = $(TARGETDIR)/test.coverage
  DEFINES   += -DNDEBUG -DRELEASE -DPLATFORM_CHECKED -DUNIX_BUILD -DOOLUA_RUNTIME_CHECKS_ENABLED=1 -DOOLUA_STD_STRING_IS_INTEGRAL=1 -DOOLUA_SAFE_ID_COMPARE=1 -DOOLUA_STORE_LAST_ERROR=0 -DOOLUA_USE_EXCEPTIONS=1
  INCLUDES  += -Iinclude/cppunit -Iinclude/gmock -Iinclude/lua -Iinclude -I/usr/local/include -I/usr/include -I../include -Ibind_classes -Icpp_classes -Itest_classes
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -Wall -W -Wall -ansi -pedantic -std=c++98 -fprofile-arcs -ftest-coverage
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -Lusr/local/lib -Lusr/lib
  LIBS      += -lgmock -lpthread -lcppunit -llua -ldl -lgcov
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running post-build commands
	$(TARGET)
  endef
endif

OBJECTS := \
	$(OBJDIR)/oolua_chunk.o \
	$(OBJDIR)/oolua_push.o \
	$(OBJDIR)/stack_get.o \
	$(OBJDIR)/oolua_pull.o \
	$(OBJDIR)/oolua_exception.o \
	$(OBJDIR)/oolua_table.o \
	$(OBJDIR)/oolua_script.o \
	$(OBJDIR)/oolua_check_result.o \
	$(OBJDIR)/oolua_helpers.o \
	$(OBJDIR)/oolua_function.o \
	$(OBJDIR)/oolua_error.o \
	$(OBJDIR)/class_from_stack.o \
	$(OBJDIR)/push_pointer_internal.o \
	$(OBJDIR)/oolua_stack_dump.o \
	$(OBJDIR)/oolua_string.o \
	$(OBJDIR)/oolua_ref.o \
	$(OBJDIR)/oolua_registration.o \
	$(OBJDIR)/proxy_storage.o \
	$(OBJDIR)/oolua_open.o \
	$(OBJDIR)/oolua.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/expose_enum.o \
	$(OBJDIR)/expose_false_integral_function_returns.o \
	$(OBJDIR)/expose_class_ops.o \
	$(OBJDIR)/expose_vector_int.o \
	$(OBJDIR)/expose_integral_function_returns.o \
	$(OBJDIR)/expose_class_constructors.o \
	$(OBJDIR)/expose_method_returns_class.o \
	$(OBJDIR)/expose_static_and_c_functions.o \
	$(OBJDIR)/expose_class_enums.o \
	$(OBJDIR)/expose_hierarchy.o \
	$(OBJDIR)/expose_out_params.o \
	$(OBJDIR)/expose_userdata_function_params.o \
	$(OBJDIR)/expose_integral_function_params.o \
	$(OBJDIR)/expose_const_func.o \
	$(OBJDIR)/expose_false_integral_function_params.o \
	$(OBJDIR)/expose_userdata_function_returns.o \
	$(OBJDIR)/expose_max_params.o \
	$(OBJDIR)/expose_ownership.o \
	$(OBJDIR)/expose_stub_classes.o \
	$(OBJDIR)/expose_namespaced_class.o \
	$(OBJDIR)/expose_public_instances.o \
	$(OBJDIR)/cpp_public_instances.o \
	$(OBJDIR)/cpp_userdata_function_returns.o \
	$(OBJDIR)/cpp_constructor_mock.o \
	$(OBJDIR)/cpp_private_destructor.o \
	$(OBJDIR)/table.o \
	$(OBJDIR)/hierarchy.o \
	$(OBJDIR)/integral_function_param_types.o \
	$(OBJDIR)/static_function.o \
	$(OBJDIR)/vector_int.o \
	$(OBJDIR)/integral_function_out_params.o \
	$(OBJDIR)/integral_function_returns.o \
	$(OBJDIR)/enum_tests.o \
	$(OBJDIR)/operators.o \
	$(OBJDIR)/error_check.o \
	$(OBJDIR)/exchange_lua2cpp.o \
	$(OBJDIR)/hello_moon.o \
	$(OBJDIR)/oolua_module.o \
	$(OBJDIR)/class_method_returns_class.o \
	$(OBJDIR)/userdata_function_out_params.o \
	$(OBJDIR)/lua_globals.o \
	$(OBJDIR)/false_integral_function_params.o \
	$(OBJDIR)/out_params.o \
	$(OBJDIR)/false_integral_function_returns.o \
	$(OBJDIR)/userdata.o \
	$(OBJDIR)/exchange_cpp2lua.o \
	$(OBJDIR)/set_ownership.o \
	$(OBJDIR)/traits.o \
	$(OBJDIR)/class_member_enums.o \
	$(OBJDIR)/destruct.o \
	$(OBJDIR)/userdata_function_params.o \
	$(OBJDIR)/namespaced_class.o \
	$(OBJDIR)/public_variables.o \
	$(OBJDIR)/construct.o \
	$(OBJDIR)/class_exchange.o \
	$(OBJDIR)/oolua_tests_pch.o \
	$(OBJDIR)/lua_caller.o \
	$(OBJDIR)/userdata_function_returns.o \
	$(OBJDIR)/metatable_check.o \
	$(OBJDIR)/max_params.o \
	$(OBJDIR)/return_order.o \
	$(OBJDIR)/light_ud.o \
	$(OBJDIR)/push_pull.o \
	$(OBJDIR)/const_functions.o \
	$(OBJDIR)/string_as_integral.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking test.coverage
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning test.coverage
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/oolua_chunk.o: ../src/oolua_chunk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_push.o: ../src/oolua_push.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/stack_get.o: ../src/stack_get.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_pull.o: ../src/oolua_pull.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_exception.o: ../src/oolua_exception.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_table.o: ../src/oolua_table.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_script.o: ../src/oolua_script.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_check_result.o: ../src/oolua_check_result.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_helpers.o: ../src/oolua_helpers.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_function.o: ../src/oolua_function.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_error.o: ../src/oolua_error.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/class_from_stack.o: ../src/class_from_stack.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/push_pointer_internal.o: ../src/push_pointer_internal.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_stack_dump.o: ../src/oolua_stack_dump.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_string.o: ../src/oolua_string.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_ref.o: ../src/oolua_ref.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_registration.o: ../src/oolua_registration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/proxy_storage.o: ../src/proxy_storage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_open.o: ../src/oolua_open.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua.o: ../src/oolua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_enum.o: bind_classes/expose_enum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_false_integral_function_returns.o: bind_classes/expose_false_integral_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_class_ops.o: bind_classes/expose_class_ops.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_vector_int.o: bind_classes/expose_vector_int.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_integral_function_returns.o: bind_classes/expose_integral_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_class_constructors.o: bind_classes/expose_class_constructors.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_method_returns_class.o: bind_classes/expose_method_returns_class.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_static_and_c_functions.o: bind_classes/expose_static_and_c_functions.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_class_enums.o: bind_classes/expose_class_enums.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_hierarchy.o: bind_classes/expose_hierarchy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_out_params.o: bind_classes/expose_out_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_userdata_function_params.o: bind_classes/expose_userdata_function_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_integral_function_params.o: bind_classes/expose_integral_function_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_const_func.o: bind_classes/expose_const_func.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_false_integral_function_params.o: bind_classes/expose_false_integral_function_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_userdata_function_returns.o: bind_classes/expose_userdata_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_max_params.o: bind_classes/expose_max_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_ownership.o: bind_classes/expose_ownership.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_stub_classes.o: bind_classes/expose_stub_classes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_namespaced_class.o: bind_classes/expose_namespaced_class.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/expose_public_instances.o: bind_classes/expose_public_instances.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/cpp_public_instances.o: cpp_classes/cpp_public_instances.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/cpp_userdata_function_returns.o: cpp_classes/cpp_userdata_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/cpp_constructor_mock.o: cpp_classes/cpp_constructor_mock.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/cpp_private_destructor.o: cpp_classes/cpp_private_destructor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/table.o: test_classes/table.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/hierarchy.o: test_classes/hierarchy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/integral_function_param_types.o: test_classes/integral_function_param_types.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/static_function.o: test_classes/static_function.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/vector_int.o: test_classes/vector_int.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/integral_function_out_params.o: test_classes/integral_function_out_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/integral_function_returns.o: test_classes/integral_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/enum_tests.o: test_classes/enum_tests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/operators.o: test_classes/operators.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/error_check.o: test_classes/error_check.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/exchange_lua2cpp.o: test_classes/exchange_lua2cpp.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/hello_moon.o: test_classes/hello_moon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_module.o: test_classes/oolua_module.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/class_method_returns_class.o: test_classes/class_method_returns_class.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/userdata_function_out_params.o: test_classes/userdata_function_out_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/lua_globals.o: test_classes/lua_globals.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/false_integral_function_params.o: test_classes/false_integral_function_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/out_params.o: test_classes/out_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/false_integral_function_returns.o: test_classes/false_integral_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/userdata.o: test_classes/userdata.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/exchange_cpp2lua.o: test_classes/exchange_cpp2lua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/set_ownership.o: test_classes/set_ownership.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/traits.o: test_classes/traits.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/class_member_enums.o: test_classes/class_member_enums.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/destruct.o: test_classes/destruct.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/userdata_function_params.o: test_classes/userdata_function_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/namespaced_class.o: test_classes/namespaced_class.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/public_variables.o: test_classes/public_variables.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/construct.o: test_classes/construct.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/class_exchange.o: test_classes/class_exchange.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/oolua_tests_pch.o: test_classes/oolua_tests_pch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/lua_caller.o: test_classes/lua_caller.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/userdata_function_returns.o: test_classes/userdata_function_returns.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/metatable_check.o: test_classes/metatable_check.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/max_params.o: test_classes/max_params.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/return_order.o: test_classes/return_order.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/light_ud.o: test_classes/light_ud.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/push_pull.o: test_classes/push_pull.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/const_functions.o: test_classes/const_functions.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/string_as_integral.o: string_is_integral/string_as_integral.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
